name: CI
on:
  pull_request:
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
      - name: yarn> Install node modules
        run: yarn --frozen-lockfile
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: pip> Install dependencies
        run: pip install -r requirements.txt
      - name: Lint app & client
        run: |
          black --check app.py
          flake8 app.py
          yarn prettier:check
      - name: Build client
        run: yarn run build
